-- Controlled sample dataset for Week 3 hybrid search testing

-- Clear existing test data
DELETE FROM documents WHERE id LIKE 'test-%';

-- Sample Email Documents
INSERT INTO documents (id, type, title, content, app_source, source_id, source_path, hash, created_at, updated_at, last_seen_at, deleted) VALUES 
('test-email-apollo', 'email', 'Project Apollo Status Update', 'Subject: Project Apollo Status Update - March Milestone Review. Hi Team, I wanted to provide you with a comprehensive update on Project Apollo as we approach our March milestone. Current Status: Backend API development 85% complete, Frontend components 70% complete, Database migration scripts 100% complete, Integration testing 60% complete. Key Achievements This Sprint: Successfully implemented user authentication system, Completed core data models and relationships, Set up CI/CD pipeline with automated testing. Budget Status: Current spend $127,000 of $180,000 allocated, On track to deliver within budget constraints. Sarah Chen Project Manager', 'Mail', 'apollo-email-001', 'message://apollo-status-march-2024', 'hash-apollo-email', 1710444000, 1710444000, 1710444000, 0),

('test-email-budget', 'email', 'Budget Review Q2 - Action Required', 'Subject: Budget Review Q2 - Action Required. Team, As we prepare for our Q2 budget review meeting scheduled for next week, I need everyone to submit their departmental budget requests by Friday. Q2 Budget Review Process: Submit initial budget requests, Department head review and consolidation, Executive review meeting, Final budget approval. Key Areas of Focus: Infrastructure and tooling investments, Team expansion requirements, Training and development allocations, Marketing and sales support. Budget Guidelines: Maximum 15% increase from Q1 approved budget. Michael Rodriguez Finance Director', 'Mail', 'budget-q2-001', 'message://budget-review-q2-2024', 'hash-budget-email', 1710358000, 1710358000, 1710358000, 0),

('test-note-1on1', 'note', '1:1 with Jon Larsen - Action Items', 'Meeting Date: March 10, 2024. Attendees: Jon Larsen Engineering Manager, Alex Kim Senior Developer. Discussion Topics: Current Project Status - Jon provided update on microservices migration, 3 out of 5 services successfully migrated, Performance improvements of 40% observed. Team Capacity and Workload - Team is currently at 95% capacity, Need to consider bringing in contractor for Q2 surge. Action Items: Jon Schedule architecture review meeting by March 15, Alex Complete performance benchmarking by March 18, Interview contractor candidates by March 22. Next Meeting: March 17, 2024 at 2:00 PM.', 'Notes', 'note-1on1-larsen', 'x-coredata://note-1on1-jon-larsen-march', 'hash-note-1on1', 1710108000, 1710108000, 1710108000, 0),

('test-note-design', 'note', 'Design Decisions: Sync vs Async Processing', 'Design Decision Log: Synchronous vs Asynchronous Processing. Date: March 12, 2024. Problem Statement: Our current data processing pipeline handles user uploads synchronously, causing timeout issues for large files and poor user experience during peak hours. Decision: Implement Asynchronous Processing with Queue. Rationale: User experience improvement is critical for retention, Scalability requirements for Q2 growth projections, Infrastructure cost increase is acceptable. Implementation Plan: Set up Redis cluster for job queue, Implement job worker processes, Add job status tracking to database.', 'Notes', 'note-design-sync-async', 'x-coredata://note-design-decisions-sync-async', 'hash-note-design', 1710194000, 1710194000, 1710194000, 0),

('test-event-offsite', 'event', 'Team Offsite Planning - Q2 Strategy', 'Event: Team Offsite Planning - Q2 Strategy Session. Date: March 22, 2024. Time: 9:00 AM - 5:00 PM PST. Location: Redwood Conference Center, 1455 El Camino Real, Palo Alto, CA. Attendees: Sarah Chen Project Manager, Jon Larsen Engineering Manager, Michael Rodriguez Finance Director, Lisa Wang Product Manager. Agenda: Q1 Retrospective, Q2 Strategy Planning, Team Building Activity, Q2 Goal Setting. Logistics: Transportation shuttle service from office, Catering breakfast pastries lunch afternoon snacks, Free on-site parking available.', 'Calendar', 'event-offsite-q2-2024', 'x-apple-eventkit://event-team-offsite-march', 'hash-event-offsite', 1711094400, 1711094400, 1711094400, 0),

('test-file-roadmap', 'file', 'Roadmap.md - Product Development Plan', 'Product Development Roadmap 2024. Executive Summary: comprehensive product development strategy for 2024, focusing on user experience improvements, scalability enhancements, and market expansion. Q1 2024 Milestones: Database migration to PostgreSQL cluster, API response time optimization target 200ms, CDN implementation for static assets. Q2 2024 Roadmap: Advanced analytics dashboard for enterprise users, Real-time collaboration tools, API rate limiting and usage analytics. Success Metrics: Application uptime 99.9%, API response time 200ms P95, Monthly Active Users growth 25% QoQ.', 'Files', 'file-roadmap-2024', '/Users/team/Documents/Product/Roadmap.md', 'hash-file-roadmap', 1709251200, 1710460800, 1710460800, 0);

-- FTS index will be updated automatically by triggers

-- Verify the test data
SELECT 'Test data inserted successfully:' as message;
SELECT id, type, title, app_source FROM documents WHERE id LIKE 'test-%' ORDER BY type, id;